name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: global.json

      - name: Install vpm CLI
        run: |
          dotnet tool install --global vrchat.vpm.cli
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Run tests
        run: dotnet test tests/UnityPackageToVpm.Tests --configuration Release
